Feat/export data blurred
cbn-alpin/cbna-si-data pull request #1
Opened 2024-08-21 08:58 UTC by ch-cbna

2024-09-26 13:06 UTC, jpm-cbna requested changes
Des modifications à faire au niveau de la forme.

2024-09-26 13:06 UTC, jpm-cbna commented on simethis/bin/export_data.sh
> +    if [ -z ${blur+x} ]; then blur=false ; printMsg "blur is set to '$blur'" ;
Mettre à la ligne les commandes après `then`

2024-09-26 13:06 UTC, jpm-cbna commented on simethis/bin/export_data.sh
> +    else printMsg "blur is set to '$blur'";
Mettre à la ligne et indenté la commande après `else`

2024-09-26 13:06 UTC, jpm-cbna commented on simethis/bin/export_data.sh
> +    if [[ "${blur}" = true ]]; then blur_geom_function_path="${sql_dir}/blur_geom.sql"
Idem, à la ligne après `then` et `else`

2024-09-26 13:06 UTC, jpm-cbna commented on simethis/config/settings.default.ini
>  # Password for SFTP server authentication
Non, il faut bien garder l'interpolation de variable ici car le fichier de config de shared est chargé en amont et viendra remplacer les valeurs par défaut.

Au besoin, ces paramètres peuvent être encore surchargé dans le fichier `simethis/config/settings.ini`.

2024-09-26 13:06 UTC, jpm-cbna commented on simethis/config/settings.default.ini
> +simethis_sftp_upload_pwd="<sftp_pwd>"
Même remarque que précédemment. Laisser l'interpolation.

2024-09-26 13:06 UTC, jpm-cbna commented on simethis/data/sql/blur_geom.sql
> +				ON s.id_observation = o.id_observation
Il faudrait corriger l'indentation ici.

2024-09-26 13:06 UTC, jpm-cbna commented on simethis/data/sql/blur_geom.sql
> +        INTO geom4326
Ajouter une indentation ici.

2024-09-26 13:06 UTC, jpm-cbna commented on simethis/data/sql/blur_geom.sql
> +-- Return 10km mesh geometry
Mettre le commentaire dans la fonction juste avant DECLARE comme ça il est présent  dans la base de données également !

2024-09-26 13:06 UTC, jpm-cbna commented on simethis/data/sql/blur_geom_fake.sql
> +-- Return precise geometry
Mettre le commentaire dans la fonction juste après `$function$` comme ça il est présent  dans la base de données également !

2024-09-26 13:06 UTC, jpm-cbna commented on simethis/data/sql/synthese.sql
> +        r.meta_id_groupe = 1 AND r.id_precision != 'N' -- non localisable
Pourquoi avoir ajouter ça ?

2024-09-26 14:10 UTC, ch-cbna commented on simethis/data/sql/synthese.sql
> +        r.meta_id_groupe = 1 AND r.id_precision != 'N' -- non localisable
C'est un choix vu avec JMG, on n'importe pas les occurences dont la précision de la géométrie est non localisable (precision = N) dans GeoNature.

2024-09-26 15:15 UTC, jpm-cbna requested changes

2024-09-26 15:15 UTC, jpm-cbna commented on simethis/bin/export_data.sh
> +        then blur=false ; printMsg "blur is set to '$blur'" ;
En fait, le `then` doit rester sur la ligne précédente juste après le ;.
Tu peux aussi mettre à la ligne `printMsg ...`.

2024-09-26 15:15 UTC, jpm-cbna commented on simethis/bin/export_data.sh
> +        then blur_geom_function_path="${sql_dir}/blur_geom.sql"
Le `then` à remonter sur la ligne précédente.

2024-09-26 15:15 UTC, jpm-cbna commented on simethis/config/settings.default.ini
> +simethis_sftp_download_pwd="${simethis_sftp_download_pwd}"
Là, je ne pense pas que les variables interpolées soient bonnes. Pour `simethis_sftp_download_host` et `simethis_sftp_download_port` tu peux récupérer ${sftp_host} et ${sftp_port} qui proviennent du fichier de config de shared mais pour les deux autres, il faut forcément les définir dans un fichier fichier `setting.ini`.
C'est pour ça que ces 2 paramètres apparaissent dans le fichier `settings.sample.ini`.

En fait, actuellement, sur la branche `main` on a ce qu'il faut avoir.

2024-10-21 10:52 UTC, jpm-cbna approved these changes
OK

2024-10-21 10:52 UTC, merged